/**
 * Briefing Router - Daily Briefings for Users
 *
 * Provides access to daily briefings generated by the briefing worker.
 */

import { protectedProcedure, createTRPCRouter } from "@/trpc/init";
import prisma from "@/lib/db";
import { z } from "zod";
import { TRPCError } from "@trpc/server";

export const briefingRouter = createTRPCRouter({
  /**
   * Get today's daily briefing
   */
  getTodaysBriefing: protectedProcedure.query(async ({ ctx }) => {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const briefing = await prisma.dailyBriefing.findUnique({
      where: {
        userId_date: {
          userId: ctx.auth.user.id,
          date: today,
        },
      },
      select: {
        id: true,
        date: true,
        content: true,
        agentsSummary: true,
        sentAt: true,
        readAt: true,
        createdAt: true,
      },
    });

    return briefing;
  }),

  /**
   * Get daily briefing for a specific date
   */
  getBriefingByDate: protectedProcedure
    .input(
      z.object({
        date: z.date(),
      })
    )
    .query(async ({ ctx, input }) => {
      const targetDate = new Date(input.date);
      targetDate.setHours(0, 0, 0, 0);

      const briefing = await prisma.dailyBriefing.findUnique({
        where: {
          userId_date: {
            userId: ctx.auth.user.id,
            date: targetDate,
          },
        },
        select: {
          id: true,
          date: true,
          content: true,
          agentsSummary: true,
          sentAt: true,
          readAt: true,
          createdAt: true,
        },
      });

      if (!briefing) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "No briefing found for this date",
        });
      }

      return briefing;
    }),

  /**
   * Get recent briefings (last N days)
   */
  getRecentBriefings: protectedProcedure
    .input(
      z.object({
        limit: z.number().min(1).max(30).default(7),
      })
    )
    .query(async ({ ctx, input }) => {
      const briefings = await prisma.dailyBriefing.findMany({
        where: {
          userId: ctx.auth.user.id,
        },
        orderBy: {
          date: "desc",
        },
        take: input.limit,
        select: {
          id: true,
          date: true,
          content: true,
          agentsSummary: true,
          sentAt: true,
          readAt: true,
          createdAt: true,
        },
      });

      return briefings;
    }),

  /**
   * Mark briefing as read
   */
  markAsRead: protectedProcedure
    .input(
      z.object({
        briefingId: z.string(),
      })
    )
    .mutation(async ({ ctx, input }) => {
      // Verify ownership
      const briefing = await prisma.dailyBriefing.findUnique({
        where: { id: input.briefingId },
        select: { userId: true },
      });

      if (!briefing) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Briefing not found",
        });
      }

      if (briefing.userId !== ctx.auth.user.id) {
        throw new TRPCError({
          code: "FORBIDDEN",
          message: "You don't have permission to access this briefing",
        });
      }

      // Mark as read
      const updated = await prisma.dailyBriefing.update({
        where: { id: input.briefingId },
        data: { readAt: new Date() },
        select: {
          id: true,
          readAt: true,
        },
      });

      return updated;
    }),

  /**
   * Get briefing stats (read count, unread count)
   */
  getBriefingStats: protectedProcedure.query(async ({ ctx }) => {
    const [total, unread] = await Promise.all([
      prisma.dailyBriefing.count({
        where: { userId: ctx.auth.user.id },
      }),
      prisma.dailyBriefing.count({
        where: {
          userId: ctx.auth.user.id,
          readAt: null,
        },
      }),
    ]);

    return {
      total,
      read: total - unread,
      unread,
    };
  }),
});
